=== mwsu-csmp/curriculum/mwsu_curriculum/schema/course.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="https://csmp.missouriwestern.edu"
  xmlns="https://csmp.missouriwestern.edu"
  elementFormDefault="qualified">

  <xs:simpleType name="courseSubject">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z][A-Z][A-Z]"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="courseNumber">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9][0-9][0-9]E?"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="prerequisiteCourse">
    <xs:sequence>
      <xs:element name="subject" type="courseSubject"/>
      <xs:element name="number" type="courseNumber"/>
    </xs:sequence>
    <xs:attribute name="corequisite" type="xs:boolean" default="false"/>
    <xs:attribute name="minimumGrade" default="pass">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="A"/>
          <xs:enumeration value="B"/>
          <xs:enumeration value="C"/>
          <xs:enumeration value="pass"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>

  <xs:simpleType name="prerequisiteGeneral">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>

  <xs:complexType name="prerequisiteConjunction">
      <xs:sequence>
        <xs:element name="prerequisiteCourse" type="prerequisiteCourse" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="prerequisiteGeneral" type="prerequisiteGeneral" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="prerequisiteConjunction" type="prerequisiteConjunction" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="prerequisiteDisjunction" type="prerequisiteDisjunction" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
  </xs:complexType>

  <xs:complexType name="prerequisiteDisjunction">
      <xs:sequence>
        <xs:element name="prerequisiteCourse" type="prerequisiteCourse" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="prerequisiteGeneral" type="prerequisiteGeneral" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="prerequisiteConjunction" type="prerequisiteConjunction" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="prerequisiteDisjunction" type="prerequisiteDisjunction" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
  </xs:complexType>

  <xs:complexType name="topic" mixed="true">
    <xs:sequence>
      <xs:element name="topic" type="topic" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="covers" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:attribute name="standard" type="xs:string"/>
          <xs:attribute name="knowledgeArea" type="xs:string"/>
          <xs:attribute name="id" type="xs:string"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="course">
    <xs:complexType>
      <xs:sequence>

      <xs:element name="college">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="CSB"/>
            <xs:enumeration value="FA"/>
            <xs:enumeration value="LA"/>
            <xs:enumeration value="PS"/>
            <xs:enumeration value="WI"/>
            <xs:enumeration value="GR"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <xs:element name="subject" type="courseSubject"/>

      <xs:element name="number" type="courseNumber"/>

      <xs:element name="title" type="xs:string"/>

      <xs:element name="offered" maxOccurs="5">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="fall"/>
            <xs:enumeration value="fall-even"/>
            <xs:enumeration value="fall-odd"/>
            <xs:enumeration value="spring"/>
            <xs:enumeration value="spring-even"/>
            <xs:enumeration value="spring-odd"/>
            <xs:enumeration value="summer"/>
            <xs:enumeration value="discretion"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <xs:element name="scheduleType">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="lecture"/>
            <xs:enumeration value="lab"/>
            <xs:enumeration value="independent study"/>
            <xs:enumeration value="online"/>
            <xs:enumeration value="seminar"/>
            <xs:enumeration value="research"/>
	    <xs:enumeration value="internship"/>
            <xs:enumeration value="practicum"/>
            <xs:enumeration value="field experience"/>
            <xs:enumeration value="discussion"/>
            <xs:enumeration value="other"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <xs:element name="catalogDescription" type="xs:string"/>

      <xs:element name="prerequisites">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="prerequisiteCourse" type="prerequisiteCourse" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="prerequisiteGeneral" type="prerequisiteGeneral" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="prerequisiteConjunction" type="prerequisiteConjunction" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="prerequisiteDisjunction" type="prerequisiteDisjunction" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>


      <xs:element name="textbook" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="author" type="xs:string" maxOccurs="unbounded"/>
          </xs:sequence>
          <xs:attribute name="title" type="xs:string"/>
          <xs:attribute name="year" type="xs:string"/>
          <xs:attribute name="publisher" type="xs:string"/>
          <xs:attribute name="edition" type="xs:string" default="1"/>
          <xs:attribute name="ISBN" type="xs:string"/>
	</xs:complexType>
      </xs:element>


      <xs:element name="objectives">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="objective" maxOccurs="unbounded">
              <xs:complexType mixed="true">
                <xs:sequence>
                <xs:element name="covers" minOccurs="0" maxOccurs="unbounded">
                  <xs:complexType>
                    <xs:attribute name="standard" type="xs:string"/>
                    <xs:attribute name="knowledgeArea" type="xs:string"/>
                    <xs:attribute name="id" type="xs:string"/>
    	            </xs:complexType>
                </xs:element>
              </xs:sequence>
            </xs:complexType>
            </xs:element>
          </xs:sequence>
	      </xs:complexType>
      </xs:element>

      <xs:element name="outline">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="topic" type="topic" maxOccurs="unbounded"/>
          </xs:sequence>
	</xs:complexType>
      </xs:element>

    </xs:sequence>

    <xs:attribute name="gradingType" default="A-Z">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="A-Z"/>
	  <xs:enumeration value="CR/F"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>

    <xs:attribute name="repeatable" type="xs:boolean" default="false"/>
    <xs:attribute name="equivalentCourse" type="xs:string" default=""/>
    <xs:attribute name="creditHoursLecture" type="xs:decimal" default="3"/>
    <xs:attribute name="creditHoursLab" type="xs:decimal" default="0"/>
    <xs:attribute name="creditHoursOther" type="xs:decimal" default="0"/>
    <xs:attribute name="contactHoursLecture" type="xs:decimal" default="3"/>
    <xs:attribute name="contactHoursLab" type="xs:decimal" default="0"/>
    <xs:attribute name="contactHoursOther" type="xs:decimal" default="0"/>
    <xs:attribute name="workloadHoursLecture" type="xs:decimal" default="3"/>
    <xs:attribute name="workloadHoursLab" type="xs:decimal" default="0"/>
    <xs:attribute name="workloadHoursOther" type="xs:decimal" default="0"/>
    <xs:attribute name="workloadHoursExpected" type="xs:decimal"/>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== mwsu-csmp/curriculum/mwsu_curriculum/syllabi/2017-2018/CSC490.xml
<?xml version="1.0" encoding="UTF-8"?>
<course
  xmlns="https://csmp.missouriwestern.edu"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://csmp.missouriwestern.edu/xml/curriculum/course.xsd"
  creditHoursLecture="1"
  workloadHoursLecture="1">
  <college>LA</college>
  <subject>CSC</subject>
  <number>490</number>
  <title>Independent Research/Project</title>
  <offered>fall</offered>
  <scheduleType>lecture</scheduleType>
  <catalogDescription>
In this course students will begin applying their MWSU education towards building a career in CS. Students will learn how to navigate a career path in CS, explore alternative career paths, and explore opportunities for continuing education and professional development. Students will develop application materials and attempt entrance, exit, and / or certification exams in preparation for graduation, applying to jobs, and applying to graduate schools. 
  </catalogDescription>
  <prerequisites>
  </prerequisites>
  <objectives>
    <objective>stub</objective>
  </objectives>
  <outline>
    <topic>stub</topic>
  </outline>
</course>

=== mwsu-csmp/curriculum/mwsu_curriculum/syllabi/2019-2020/CSC406.xml
<?xml version="1.0" encoding="UTF-8"?>
<course
  xmlns="https://csmp.missouriwestern.edu"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://csmp.missouriwestern.edu/xml/curriculum/course.xsd">
  <college>LA</college>
  <subject>CSC</subject>
  <number>406</number>
  <title>Object Oriented Applications and Program Development</title>
  <offered>spring</offered>
  <scheduleType>lecture</scheduleType>
  <catalogDescription>
This course emphasizes the application of Object Oriented Programming (OOP) concepts in the java programming language to large-scale programming problems. The course includes application of techniques such as the Unified Modeling Language (UML). 
  </catalogDescription>
  <prerequisites>
    <prerequisiteCourse minimumGrade="C"><subject>CSC</subject><number>285</number></prerequisiteCourse>
    <prerequisiteCourse minimumGrade="C" corequisite="true"><subject>CSC</subject><number>305</number></prerequisiteCourse>
  </prerequisites>
  <objectives>
    <objective>stub</objective>
  </objectives>
  <outline>
    <topic>stub</topic>
  </outline>
</course>

=== mwsu-csmp/curriculum/mwsu_curriculum/syllabi/2020-2021/CSC285.xml
<?xml version="1.0" encoding="UTF-8"?>
<course
  xmlns="https://csmp.missouriwestern.edu"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://csmp.missouriwestern.edu/xml/curriculum/course.xsd">
  <college>LA</college>
  <subject>CSC</subject>
  <number>285</number>
  <title>Data Structures</title>
  <offered>fall</offered>
  <scheduleType>lecture</scheduleType>
  <catalogDescription>
Topics include algorithm analysis and the implementation of stacks, queues, linked lists, trees, and other data structures. Principles of data abstraction are emphasized throughout the course.
  </catalogDescription>
  <prerequisites>
    <prerequisiteCourse minimumGrade="C"><subject>CSC</subject><number>254</number></prerequisiteCourse>
    <prerequisiteDisjunction>
      <prerequisiteCourse minimumGrade="C"><subject>MAT</subject><number>112</number></prerequisiteCourse>
      <prerequisiteCourse minimumGrade="C"><subject>MAT</subject><number>116</number></prerequisiteCourse>
      <prerequisiteCourse minimumGrade="C"><subject>MAT</subject><number>147</number></prerequisiteCourse>
      <prerequisiteCourse minimumGrade="C"><subject>MAT</subject><number>165</number></prerequisiteCourse>
      <prerequisiteCourse minimumGrade="C"><subject>MAT</subject><number>167</number></prerequisiteCourse>
    </prerequisiteDisjunction>
  </prerequisites>
  <objectives>
    <objective>stub</objective>
  </objectives>
  <outline>
    <topic>stub</topic>
  </outline>
</course>

=== mwsu-csmp/curriculum/mwsu_curriculum/syllabi/2019-2020/CSC245.xml
<?xml version="1.0" encoding="UTF-8"?>
<course
  xmlns="https://csmp.missouriwestern.edu"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://csmp.missouriwestern.edu/xml/curriculum/course.xsd">
  <college>LA</college>
  <subject>CSC</subject>
  <number>245</number>
  <title>Enterprise Systems Computing: COBOL I</title>
  <offered>fall-even</offered>
  <scheduleType>lecture</scheduleType>
  <catalogDescription>
This course explores the structure of the COBOL programming language, to include basic syntax, flow control, record and memory structures, input/output and report writing. A real-world enterprise system environment will be used to provide exposure to JCL and various tools that support business processes and information flow. 
  </catalogDescription>
  <prerequisites>
    <prerequisiteCourse minimumGrade="C"><subject>CSC</subject><number>254</number></prerequisiteCourse>
  </prerequisites>
  <objectives>
    <objective>stub</objective>
  </objectives>
  <outline>
    <topic>stub</topic>
  </outline>
</course>

=== mwsu-csmp/curriculum/mwsu_curriculum/syllabi/2021-2022/CSC254.xml
<?xml version="1.0" encoding="UTF-8"?>
<course
  xmlns="https://csmp.missouriwestern.edu"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://csmp.missouriwestern.edu/xml/curriculum/course.xsd">
  <college>LA</college>
  <subject>CSC</subject>
  <number>254</number>
  <title>Object Oriented Programming</title>
  <offered>fall</offered>
  <offered>spring</offered>
  <scheduleType>lecture</scheduleType>
  <catalogDescription>
    This course is a continuation of CSC 184 and introduces the Java programming language. Java is used to introduce Object Oriented Programming concepts including data abstraction, classes, inheritance, and polymorphism. Other programming topics covered include multidimensional arrays and array processing, elementary sorting and searching techniques, dynamic memory allocation, linked lists, and GUI interface creating.
  </catalogDescription>
  <prerequisites>
    <prerequisiteCourse minimumGrade="C"><subject>CSC</subject><number>184</number></prerequisiteCourse>
  </prerequisites>

  <objectives>
    <objective>Construct a simple user interface using a standard API.
      <covers standard="acm-cs2013" knowledgeArea="GV/FC" id="4"/>
    </objective>
    <objective>Demonstrate the identification and graceful handling of error conditions.
      <covers standard="acm-cs2013" knowledgeArea="IAS/DP" id="5"/>
    </objective>
    <objective>Describe the main concepts of the OO model.
      <covers standard="acm-cs2013" knowledgeArea="IM/DM" id="6"/>
    </objective>
    <objective>Design and implement a class.
      <covers standard="acm-cs2013" knowledgeArea="PL/OP" id="1"/>
    </objective>
    <objective>Use subclassing to design simple class hierarchies that allow code to be reused for distinct subclasses.
      <covers standard="acm-cs2013" knowledgeArea="PL/OP" id="2"/>
    </objective>
    <objective>Correctly reason about control flow in a program using dynamic dispatch.
      <covers standard="acm-cs2013" knowledgeArea="PL/OP" id="3"/>
    </objective>
    <objective>Explain the relationship between object-oriented inheritance (code-sharing and overriding) and subtyping (the idea of a subtype being usable in a context that expects the supertype).
      <covers standard="acm-cs2013" knowledgeArea="PL/OP" id="5"/>
    </objective>
    <objective>Use object-oriented encapsulation mechanisms such as interfaces and private members.
    </objective>
    <objective>Write event handlers for use in reactive systems, such as GUIs.
      <covers standard="acm-cs2013" knowledgeArea="PL/EARP" id="1"/>
    </objective>
    <objective>For a language with a static type system, describe the operations that are forbidden statically, such as passing the wrong type of value to a function or method.
      <covers standard="acm-cs2013" knowledgeArea="PL/BTS" id="2"/>
    </objective>
    <objective>Explain how typing rules define the set of operations that are legal for a type.
      <covers standard="acm-cs2013" knowledgeArea="PL/BTS" id="7"/>
    </objective>
    <objective>Define and use program pieces (such as functions, classes, methods) that use generic types, including for collections.
      <covers standard="acm-cs2013" knowledgeArea="PL/BTS" id="10"/>
    </objective>
    <objective>Discuss the differences among generics, subtyping, and overloading.
      <covers standard="acm-cs2013" knowledgeArea="PL/BTS" id="11"/>
    </objective>
    <objective>Identify the data components and behaviors of multiple abstract data types.
      <covers standard="acm-cs2013" knowledgeArea="SDF/AAD" id="9"/>
    </objective>
    <objective>Implement a coherent abstract data type, with loose coupling between components and behaviors.
      <covers standard="acm-cs2013" knowledgeArea="SDF/AAD" id="10"/>
    </objective>
  </objectives>
  <outline>
    <topic>Single Dimensional Arrays
        <topic>Array Declarations and Initialization</topic>
        <topic>Processing Array Information</topic>
        <topic>Sorting and Searching an Array</topic>
        <topic>Multidimensional Arrays in Java</topic>
    </topic>
      <topic>Objects and Classes
          <topic>Programming Concepts</topic>
          <topic>Class Declaration</topic>
          <topic>UML</topic>
          <topic>Object initialization using constructors</topic>
          <topic>Object reference variables</topic>
          <topic>Static variables</topic>
          <topic>Visibility Modifiers and Access/Mutator Methods</topic>
          <topic>Passing Objects to Methods</topic>
          <topic>Array of Objects</topic>
      </topic>
      <topic>String and Text
          <topic>Java API Classes for String Manipulation</topic>
          <topic>File based Text I/O</topic>
      </topic>
      <topic>Inheritance and Polymorphism
          <topic>Superclass and Subclass</topic>
          <topic>Method Overriding</topic>
          <topic>toString and equals methods in Object class</topic>
          <topic>Polymorphism, dynamic binding and generic programming</topic>
          <topic>Casting</topic>
          <topic>The “protected” and “final” visibility modifiers</topic>
      </topic>
      <topic>Abstract Classes and Interfaces
          <topic>Abstract Classes and Abstract Methods</topic>
          <topic>Definition of an Interface</topic>
          <topic>Interfaces vs. Abstract Classes</topic>
          <topic>Wrapper Classes</topic>
      </topic>
      <topic>Exception Handling</topic>
      <topic>GUI Basics</topic>
  </outline>
</course>

=== mwsu-csmp/curriculum/mwsu_curriculum/syllabi/2019-2020/CSC328.xml
<?xml version="1.0" encoding="UTF-8"?>
<course
  xmlns="https://csmp.missouriwestern.edu"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://csmp.missouriwestern.edu/xml/curriculum/course.xsd">
  <college>LA</college>
  <subject>CSC</subject>
  <number>328</number>
  <title>Computer Graphics</title>
  <offered>spring</offered>
  <scheduleType>lecture</scheduleType>
  <catalogDescription>
	  stub
  </catalogDescription>
  <prerequisites>
    <prerequisiteCourse minimumGrade="C"><subject>CSC</subject><number>285</number></prerequisiteCourse>
  </prerequisites>
  <objectives>
    <objective>stub</objective>
  </objectives>
  <outline>
    <topic>stub</topic>
  </outline>
</course>

=== mwsu-csmp/curriculum/mwsu_curriculum/syllabi/2021-2022/SEC415.xml
<?xml version="1.0" encoding="UTF-8"?>
<course
  xmlns="https://csmp.missouriwestern.edu"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://csmp.missouriwestern.edu/xml/curriculum/course.xsd">
  <college>LA</college>
  <subject>SEC</subject>
  <number>415</number>
  <title>Data Security and Identity Management</title>
  <offered>spring</offered>
  <scheduleType>lecture</scheduleType>
  <catalogDescription>
stub
  </catalogDescription>
  <prerequisites>
  </prerequisites>

  <objectives>
    <objective>Describe the following terms: cipher, cryptanalysis, cryptographic algorithm, and cryptology, and describe the two basic methods (ciphers) for transforming plaintext in ciphertext.
      <covers standard="acm-csec2017" knowledgeArea="1/1" id="2"/>
    </objective>
    <objective>Describe which cryptographic protocols, tools and techniques are appropriate for a given situation.
      <covers standard="acm-csec2017" knowledgeArea="1/1" id="5"/>
    </objective>
    <objective>Discuss the dangers of inventing oneâ€™s own cryptographic methods.
      <covers standard="acm-csec2017" knowledgeArea="1/1" id="4"/>
    </objective>
    <objective>Explain the concepts of authentication, authorization, access control, and data integrity.
      <covers standard="acm-csec2017" knowledgeArea="1/3" id="1"/>
    </objective>
    <objective>Explain the various authentication techniques and their strengths and weaknesses.
      <covers standard="acm-csec2017" knowledgeArea="1/3" id="2"/>
    </objective>
    <objective>Explain the various possible attacks on passwords.
      <covers standard="acm-csec2017" knowledgeArea="1/3" id="3"/>
    </objective>
    <objective>Describe the various techniques for data erasure.
      <covers standard="acm-csec2017" knowledgeArea="1/8" id="1"/>
    </objective>
    <objective>Describe the concept of privacy including personally identifiable information.
      <covers standard="acm-csec2017" knowledgeArea="2/2" id="4"/>
    </objective>
    <objective>Explain the difference between identification, authentication, and access authorization of people and devices.
      <covers standard="acm-csec2017" knowledgeArea="6/1" id="1"/>
    </objective>
    <objective>Discuss the importance of audit trails and logging in identification and authentication.
      <covers standard="acm-csec2017" knowledgeArea="6/1" id="2"/>
    </objective>
    <objective>Demonstrate the ability to implement the concept of least privilege and segregation of duties.
      <covers standard="acm-csec2017" knowledgeArea="6/1" id="3"/>
    </objective>
    <objective>Demonstrate the overall understanding of access control attacks and mitigation measures.
      <covers standard="acm-csec2017" knowledgeArea="6/1" id="4"/>
    </objective>
    <objective>Discuss the importance of protection of Sensitive Personal Data (SPD) and Personally Identifiable Information (PII).
      <covers standard="acm-csec2017" knowledgeArea="6/6" id="1"/>
    </objective>
    <objective>Discuss the importance of regulations governing the collection, use and distribution of SPD, and possibilities for inference of SPD.
      <covers standard="acm-csec2017" knowledgeArea="6/6" id="2"/>
    </objective>
    <objective>Describe the concepts of personal tracking and digital footprint, while understanding the invasiveness of such tools in the context of privacy.
      <covers standard="acm-csec2017" knowledgeArea="6/6" id="3"/>
    </objective>
    <objective>Compare and contrast various theories of privacy from social psychology and social science.
      <covers standard="acm-csec2017" knowledgeArea="6/5" id="1"/>
    </objective>
    <objective>Explain three properties commonly used for authentication.
      <covers standard="acm-csec2017" knowledgeArea="5" id="7"/>
    </objective>
    <objective>Explain the importance of multifactor authentication.
      <covers standard="acm-csec2017" knowledgeArea="5" id="8"/>
    </objective>
    <objective>Explain the advantages of pass phrases over passwords.
      <covers standard="acm-csec2017" knowledgeArea="5" id="9"/>
    </objective>
    <objective>Describe physical and logical access control, and compare and contrast them.
      <covers standard="acm-csec2017" knowledgeArea="5" id="11"/>
    </objective>
    <objective>Distinguish between authorization and authentication.
      <covers standard="acm-csec2017" knowledgeArea="5" id="12"/>
    </objective>
    <objective>Explain why backups pose a potential security risk.
      <covers standard="acm-csec2017" knowledgeArea="5" id="18"/>
    </objective>
  </objectives>
  <outline>
    <topic>Introduction
    </topic>
  </outline>
</course>

=== mwsu-csmp/curriculum/mwsu_curriculum/syllabi/2021-2022/CSC400.xml
<?xml version="1.0" encoding="UTF-8"?>
<course
  xmlns="https://csmp.missouriwestern.edu"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://csmp.missouriwestern.edu/xml/curriculum/course.xsd">
  <college>LA</college>
  <subject>CSC</subject>
  <number>400</number>
  <title>Systems Analysis and Design</title>
  <offered>fall</offered>
  <scheduleType>lecture</scheduleType>
  <catalogDescription>
Study of structured systems development. Emphasis on strategies and techniques of structured analysis and object oriented design for producing logical methodologies for dealing with the development of information systems.
  </catalogDescription>
  <prerequisites>
    <prerequisiteCourse minimumGrade="C" corequisite="true"><subject>CSC</subject><number>254</number></prerequisiteCourse>
  </prerequisites>
  <objectives>
    <objective>stub</objective>
  </objectives>
  <outline>
    <topic>Project Selection and Client Sponsor approval</topic>
    <topic>Request for Service and Project Charter</topic>
    <topic>Risk analysis and project budget</topic>
    <topic>UML analysis documents and schedules</topic>
    <topic>Use Case development through level III</topic>
    <topic>Constraint documentation</topic>
    <topic>Work Breakdown Schedule</topic>
    <topic>Inventory of personnel, hardware, software and all tools used to develop your project.</topic>
    <topic>Database analysis and implementation</topic>
    <topic>Human Factors Analysis and wireframes</topic>
    <topic>User Screen Prototype creation</topic>
  </outline>
</course>
