=== mwsu-csmp/curriculum/mwsu_curriculum/schema/course.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="https://csmp.missouriwestern.edu"
  xmlns="https://csmp.missouriwestern.edu"
  elementFormDefault="qualified">

  <xs:simpleType name="courseSubject">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z][A-Z][A-Z]"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="courseNumber">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9][0-9][0-9]E?"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="prerequisiteCourse">
    <xs:sequence>
      <xs:element name="subject" type="courseSubject"/>
      <xs:element name="number" type="courseNumber"/>
    </xs:sequence>
    <xs:attribute name="corequisite" type="xs:boolean" default="false"/>
    <xs:attribute name="minimumGrade" default="pass">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="A"/>
          <xs:enumeration value="B"/>
          <xs:enumeration value="C"/>
          <xs:enumeration value="pass"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>

  <xs:simpleType name="prerequisiteGeneral">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>

  <xs:complexType name="prerequisiteConjunction">
      <xs:sequence>
        <xs:element name="prerequisiteCourse" type="prerequisiteCourse" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="prerequisiteGeneral" type="prerequisiteGeneral" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="prerequisiteConjunction" type="prerequisiteConjunction" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="prerequisiteDisjunction" type="prerequisiteDisjunction" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
  </xs:complexType>

  <xs:complexType name="prerequisiteDisjunction">
      <xs:sequence>
        <xs:element name="prerequisiteCourse" type="prerequisiteCourse" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="prerequisiteGeneral" type="prerequisiteGeneral" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="prerequisiteConjunction" type="prerequisiteConjunction" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="prerequisiteDisjunction" type="prerequisiteDisjunction" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
  </xs:complexType>

  <xs:complexType name="topic" mixed="true">
    <xs:sequence>
      <xs:element name="topic" type="topic" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="covers" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:attribute name="standard" type="xs:string"/>
          <xs:attribute name="knowledgeArea" type="xs:string"/>
          <xs:attribute name="id" type="xs:string"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="course">
    <xs:complexType>
      <xs:sequence>

      <xs:element name="college">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="CSB"/>
            <xs:enumeration value="FA"/>
            <xs:enumeration value="LA"/>
            <xs:enumeration value="PS"/>
            <xs:enumeration value="WI"/>
            <xs:enumeration value="GR"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <xs:element name="subject" type="courseSubject"/>

      <xs:element name="number" type="courseNumber"/>

      <xs:element name="title" type="xs:string"/>

      <xs:element name="offered" maxOccurs="5">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="fall"/>
            <xs:enumeration value="fall-even"/>
            <xs:enumeration value="fall-odd"/>
            <xs:enumeration value="spring"/>
            <xs:enumeration value="spring-even"/>
            <xs:enumeration value="spring-odd"/>
            <xs:enumeration value="summer"/>
            <xs:enumeration value="discretion"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <xs:element name="scheduleType">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="lecture"/>
            <xs:enumeration value="lab"/>
            <xs:enumeration value="independent study"/>
            <xs:enumeration value="online"/>
            <xs:enumeration value="seminar"/>
            <xs:enumeration value="research"/>
	    <xs:enumeration value="internship"/>
            <xs:enumeration value="practicum"/>
            <xs:enumeration value="field experience"/>
            <xs:enumeration value="discussion"/>
            <xs:enumeration value="other"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <xs:element name="catalogDescription" type="xs:string"/>

      <xs:element name="prerequisites">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="prerequisiteCourse" type="prerequisiteCourse" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="prerequisiteGeneral" type="prerequisiteGeneral" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="prerequisiteConjunction" type="prerequisiteConjunction" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="prerequisiteDisjunction" type="prerequisiteDisjunction" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>


      <xs:element name="textbook" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="author" type="xs:string" maxOccurs="unbounded"/>
          </xs:sequence>
          <xs:attribute name="title" type="xs:string"/>
          <xs:attribute name="year" type="xs:string"/>
          <xs:attribute name="publisher" type="xs:string"/>
          <xs:attribute name="edition" type="xs:string" default="1"/>
          <xs:attribute name="ISBN" type="xs:string"/>
	</xs:complexType>
      </xs:element>


      <xs:element name="objectives">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="objective" maxOccurs="unbounded">
              <xs:complexType mixed="true">
                <xs:sequence>
                <xs:element name="covers" minOccurs="0" maxOccurs="unbounded">
                  <xs:complexType>
                    <xs:attribute name="standard" type="xs:string"/>
                    <xs:attribute name="knowledgeArea" type="xs:string"/>
                    <xs:attribute name="id" type="xs:string"/>
    	            </xs:complexType>
                </xs:element>
              </xs:sequence>
            </xs:complexType>
            </xs:element>
          </xs:sequence>
	      </xs:complexType>
      </xs:element>

      <xs:element name="outline">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="topic" type="topic" maxOccurs="unbounded"/>
          </xs:sequence>
	</xs:complexType>
      </xs:element>

    </xs:sequence>

    <xs:attribute name="gradingType" default="A-Z">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="A-Z"/>
	  <xs:enumeration value="CR/F"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>

    <xs:attribute name="repeatable" type="xs:boolean" default="false"/>
    <xs:attribute name="equivalentCourse" type="xs:string" default=""/>
    <xs:attribute name="creditHoursLecture" type="xs:decimal" default="3"/>
    <xs:attribute name="creditHoursLab" type="xs:decimal" default="0"/>
    <xs:attribute name="creditHoursOther" type="xs:decimal" default="0"/>
    <xs:attribute name="contactHoursLecture" type="xs:decimal" default="3"/>
    <xs:attribute name="contactHoursLab" type="xs:decimal" default="0"/>
    <xs:attribute name="contactHoursOther" type="xs:decimal" default="0"/>
    <xs:attribute name="workloadHoursLecture" type="xs:decimal" default="3"/>
    <xs:attribute name="workloadHoursLab" type="xs:decimal" default="0"/>
    <xs:attribute name="workloadHoursOther" type="xs:decimal" default="0"/>
    <xs:attribute name="workloadHoursExpected" type="xs:decimal"/>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== mwsu-csmp/curriculum/mwsu_curriculum/syllabi/2019-2020/CSC625.xml
<?xml version="1.0" encoding="UTF-8"?>
<course
  xmlns="https://csmp.missouriwestern.edu"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://csmp.missouriwestern.edu/xml/curriculum/course.xsd">
  <college>LA</college>
  <subject>CSC</subject>
  <number>625</number>
  <title>Network Information Systems Security</title>
  <offered>fall</offered>
  <scheduleType>lecture</scheduleType>
  <catalogDescription>
This course is designed to instruct students on various facets of network security and to introduce students to the tools that are available to secure and monitor TCP/IP-based networks. Students will have an opportunity to see both commercial and open source tools in action and to learn about the technology behind each tool. Some of the technologies discussed include public keys cryptography, firewalls, authentication, intrusion detection and control of malicious code. Students also learn about OS hardening fundamentals as well as security assessment tools and techniques. A research project is required.
  </catalogDescription>
  <prerequisites>
  </prerequisites>
  <objectives>
    <objective>To identify and eliminate threats in wired and wireless networks</objective>
    <objective>To restrict, monitor and audit network access</objective>
    <objective>To secure network access on the application layer of the OSI model</objective>
  </objectives>
  <outline>
    <topic>Network Security
	<topic>Understand the fundamentals of network design including network elements, network addressing, and network zoning.</topic>
	<topic>Identify threats associated with common networking protocols</topic>
	<topic>Secure wired and wireless network against different forms of malicious attacks using different network security concepts.</topic>
    </topic>
    <topic>Authentication, Access Control, Risk Management and Assessment, Monitoring and Auditing
	<topic>Apply models to authenticate a person prior to granting accesses to resources</topic>
	<topic>Design security policies based on access control models</topic>
	<topic>Understand common access models and identify their differences</topic>
	<topic>Create plans of action to enforce security policies</topic>
	<topic>Conduct risk assessments and vulnerability assessments with security tools</topic>
	<topic>Understand common network monitoring methodologies. Apply monitoring tools on hosts and networks</topic>
	<topic>Audit resource usage and log user activities for security breach investigations</topic>
    </topic>
    <topic>Web Security
	<topic>Understand common browser security models and mechanisms</topic>
	<topic>Apprehend server-side authentication and session management</topic>
	<topic>Recognize common vulnerability and attacks to web-application servers</topic>
	<topic>Comprehend secure browser-sever communication based on encryption techniques</topic>
    </topic>
  </outline>
</course>

=== mwsu-csmp/curriculum/mwsu_curriculum/syllabi/2021-2022/SEC455.xml
<?xml version="1.0" encoding="UTF-8"?>
<course
  xmlns="https://csmp.missouriwestern.edu"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://csmp.missouriwestern.edu/xml/curriculum/course.xsd">
  <college>LA</college>
  <subject>SEC</subject>
  <number>455</number>
  <title>Cyberlaw and Investigations</title>
  <offered>spring</offered>
  <scheduleType>lecture</scheduleType>
  <catalogDescription>
stub
  </catalogDescription>
  <prerequisites>
  </prerequisites>

  <objectives>
    <objective>Describe what a digital investigation is, the sources of digital evidence, and the limitations of forensics.
      <covers standard="acm-csec2017" knowledgeArea="1/2" id="1"/>
    </objective>
    <objective>Compare and contrast variety of forensics tools.
      <covers standard="acm-csec2017" knowledgeArea="1/2" id="2"/>
    </objective>
    <objective>Discuss various motives for cybercrime behavior.
      <covers standard="acm-csec2017" knowledgeArea="8/1" id="1"/>
    </objective>
    <objective>Summarize terror activities in cyberspace geared toward generating societal fear and certainty.
      <covers standard="acm-csec2017" knowledgeArea="8/1" id="2"/>
    </objective>
    <objective>Describe methods for investigating both domestic and international crimes.
      <covers standard="acm-csec2017" knowledgeArea="8/1" id="3"/>
    </objective>
    <objective>Explain why preserving the chain of digital evidence is necessary in prosecuting cybercrimes.
      <covers standard="acm-csec2017" knowledgeArea="8/1" id="4"/>
    </objective>
    <objective>Describe the constitutional foundations of cyber law.
      <covers standard="acm-csec2017" knowledgeArea="8/2" id="1"/>
    </objective>
    <objective>Describe international data security and computer hacking laws.
      <covers standard="acm-csec2017" knowledgeArea="8/2" id="2"/>
    </objective>
    <objective>Interpret intellectual property laws related to security.
      <covers standard="acm-csec2017" knowledgeArea="8/2" id="3"/>
    </objective>
    <objective>Summarize laws governing online privacy.
      <covers standard="acm-csec2017" knowledgeArea="8/2" id="4"/>
    </objective>
    <objective>Describe major international public policy positions and the impact they have on organizations and individuals.
      <covers standard="acm-csec2017" knowledgeArea="8/4" id="1"/>
    </objective>
    <objective>Summarize nation-specific cybersecurity public policy with respect to the protection of sensitive information and protection of critical infrastructure.
      <covers standard="acm-csec2017" knowledgeArea="8/4" id="2"/>
    </objective>
    <objective>Explain global impact of cybersecurity to culture including areas such as the economy, social issues, policy and laws.
      <covers standard="acm-csec2017" knowledgeArea="8/4" id="3"/>
    </objective>
    <objective>Describe the concept of privacy including the societal definition of what constitutes personally private information and the tradeoffs between individual privacy and security.
      <covers standard="acm-csec2017" knowledgeArea="8/5" id="1"/>
    </objective>
    <objective>Summarize the tradeoff between the rights to privacy by the individual versus the needs of society.
      <covers standard="acm-csec2017" knowledgeArea="8/5" id="2"/>
    </objective>
    <objective>Describe the common practices and technologies used to safeguard personal privacy.
      <covers standard="acm-csec2017" knowledgeArea="8/5" id="3"/>
    </objective>
    <objective>Differentiate between law and ethics.
      <covers standard="acm-csec2017" knowledgeArea="7/2" id="5"/>
    </objective>
    <objective>Identify significant national and international laws that relate to cybersecurity.
      <covers standard="acm-csec2017" knowledgeArea="7/2" id="7"/>
    </objective>
    <objective>Explain how organizations achieve compliance with national and international laws and regulations, and specific industry standards.
      <covers standard="acm-csec2017" knowledgeArea="7/2" id="8"/>
    </objective>
    <objective>Explain strategic organizational planning for cybersecurity and its relationship to organization-wide and IT strategic planning.
      <covers standard="acm-csec2017" knowledgeArea="7/5" id="1"/>
    </objective>
    <objective>Identify the key organizational stakeholders and their roles.
      <covers standard="acm-csec2017" knowledgeArea="7/5" id="2"/>
    </objective>
    <objective>Describe the principal components of cybersecurity system implementation planning.
      <covers standard="acm-csec2017" knowledgeArea="7/5" id="3"/>
    </objective>
  </objectives>
  <outline>
    <topic>Introduction
    </topic>
  </outline>
</course>

=== mwsu-csmp/curriculum/mwsu_curriculum/syllabi/2021-2022/SEC620.xml
<?xml version="1.0" encoding="UTF-8"?>
<course
  xmlns="https://csmp.missouriwestern.edu"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://csmp.missouriwestern.edu/xml/curriculum/course.xsd">
  <college>LA</college>
  <subject>SEC</subject>
  <number>620</number>
  <title>Cloud Computing Security</title>
  <offered>spring-even</offered>
  <scheduleType>lecture</scheduleType>
  <catalogDescription>
Enterprise-scale cloud computing is proliferating because of its cost effectiveness and enhanced resource manageability. The primary objective of this course is to equip students with solid understanding of cloud computing. It covers cloud computing and services in both business and technical viewpoints. Cloud security architecture will also be covered with an emphasis on the four major categories of security controls.
  </catalogDescription>
  <prerequisites>
    <prerequisiteDisjunction>
      <prerequisiteCourse minimumGrade="C"><subject>SEC</subject><number>300</number></prerequisiteCourse>
      <prerequisiteCourse minimumGrade="C" corequisite="true"><subject>SEC</subject><number>600</number></prerequisiteCourse>
    </prerequisiteDisjunction>
  </prerequisites>
  <objectives>
    <objective>Describe cloud characteristics, and its fundamental and technical concepts</objective>
    <objective>Identify cloud management platforms that manage virtual machines, and virtualized infrastructures and workloads</objective>
    <objective>Compare various cloud management strategies</objective>
    <objective>Apply common security concepts and tools to identify potential risks and security threats</objective>
    <objective>Differentiate well-known security measures and decide their applicability in given scenarios</objective>
  </objectives>
  <outline>
<!--
    <topic>Enterprise-scale cloud computing
	<topic>business value of cloud computing</topic>
	<topic>different types of cloud computing</topic>
	<topic>transitioning from traditional IT infrastructures to cloud computing</topic>
	<topic>identifying and handling security threats</topic>
	<topic>securing sensitive data in cloud environment</topic>
	<topic>cloud service management</topic>
    </topic>
    <topic>Cloud security architecture
	<topic>Deterrent controls</topic>
	<topic>Preventive controls</topic>
	<topic>Detective controls</topic>
	<topic>Corrective controls</topic>
    </topic>
-->
	<topic>The Basics of Cloud Computing Security
		<topic>Cloud Security Baselines</topic>
		<topic>Cloud Security, Privacy, and Trust Baselines</topic>
	</topic>
	<topic>Risk Analysis and Division of Responsibility
		<topic>Risk and Trust Assessment: Schemes for Cloud Services</topic>
		<topic>Managing Risk in the Cloud</topic>
		<topic>Cloud Security Risk Management</topic>
		<topic>Secure Cloud Risk Management: Risk Mitigation Methods</topic>
	</topic>
	<topic>Securing the Cloud Infrastructure
		<topic>Specification and Enforcement of Access Policies in Emerging Scenarios</topic>
		<topic>Cloud Security Access Control: Distributed Access Control</topic>
		<topic>Cloud Security Key Management: Cloud User Controls</topic>
		<topic>Cloud Computing Security Essentials and Architecture</topic>
		<topic>Cloud Computing Architecture and Security Concepts</topic>
		<topic>Secure Cloud Architecture</topic>
	</topic>
	<topic>Meeting Compliance Requirements
		<topic>Negotiating Cloud Security Requirements with Vendors</topic>
		<topic>Managing Legal Compliance Risk in the Cloud and Negotiating Personal Data Protection Requirements with Vendors</topic>
		<topic>Computing Technology for Trusted Cloud Security</topic>
		<topic>Trusted Computing Technology and Proposals for Resolving Cloud Computing Security Problems</topic>
	</topic>
	<topic>Preparing for Disaster Recovery
		<topic>Simplifying Secure Cloud Computing Environments with Cloud Data Centers</topic>
		<topic>Availability, Recovery, and Auditing across Data Centers</topic>
	</topic>
	<topic>Advanced Cloud Computing Security
		<topic>Advanced Security Architectures for Cloud Computing</topic>
		<topic>Side-Channel Attacks and Defenses on Cloud Traffic</topic>
		<topic>Clouds are Evil</topic>
		<topic>Future Directions in Cloud Computing Security: Risks and Challenges</topic>
	</topic>
  </outline>
</course>

=== mwsu-csmp/curriculum/mwsu_curriculum/syllabi/2020-2021/ACT490.xml
<?xml version="1.0" encoding="UTF-8"?>
<course
  xmlns="https://csmp.missouriwestern.edu"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://csmp.missouriwestern.edu/xml/curriculum/course.xsd"
  creditHoursLecture="1"
  workloadHoursLecture="1">
  <college>LA</college>
  <subject>ACT</subject>
  <number>490</number>
  <title>Information Technology Career Preparation</title>
  <offered>fall</offered>
  <scheduleType>lecture</scheduleType>
  <catalogDescription>In this course students will begin applying their MWSU education towards building a career in IT. Students will learn how to navigate a career path in IT, explore alternative career paths, and explore opportunities for continuing education and professional development. Students will develop application materials and attempt entrance, exit, and / or certification exams in preparation for graduation, applying to jobs, and applying to graduate schools. 
  </catalogDescription>
  <prerequisites>
  </prerequisites>
  <objectives>
    <objective>Determine what types of jobs in IT best match their short and long term career and professional development goals</objective>
    <objective>Locate and navigate resources for finding IT jobs in their desired location</objective>
    <objective>Effectively communicate their skill set and value as an employee to potential employers through letters, resumes, networking, interviews, and other means</objective>
    <objective>Locate and utilize resources for continuing education and professional development to gain or improve specific skillsets in IT or transition in to other career fields (ex. Law)</objective>
    <objective>Prepare effectively for certification exams, assessments, and technical interviews</objective>
  </objectives>
  <outline>
    <topic>Searching for IT employment opportunities</topic>
    <topic>Emerging and popular IT skillsets and technologies</topic>
    <topic>Communication
        <topic>Developing IT resumes</topic>
        <topic>Developing IT cover letters</topic>
        <topic>Developing a project portfolio</topic>
        <topic>Applying to graduate schools</topic>
        <topic>Developing a web and social media presence</topic>
    </topic>
    <topic>Networking
        <topic>Professional organizations</topic>
        <topic>Conferences, job fairs, and other professional gatherings</topic>
    </topic>
    <topic>Professional ethics and employment regulations</topic>
    <topic>Preparing for entrance, exit, and certification exams</topic>
  </outline>
</course>

=== mwsu-csmp/curriculum/mwsu_curriculum/syllabi/2020-2021/CSC650.xml
<?xml version="1.0" encoding="UTF-8"?>
<course
  xmlns="https://csmp.missouriwestern.edu"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://csmp.missouriwestern.edu/xml/curriculum/course.xsd">
  <college>LA</college>
  <subject>CSC</subject>
  <number>650</number>
  <title>Information Assurance</title>
  <offered>spring</offered>
  <scheduleType>lecture</scheduleType>
  <catalogDescription>
This course will explore cyber-security principles by examining security policies and procedures for managing critical and sensitive data. Implications for government compliance, professional ethics, and organizational risk management will be addressed in relation to the task of preserving the confidentiality, authenticity, integrity, and availability of such data.
  </catalogDescription>
  <prerequisites>
  </prerequisites>
  <objectives>
    <objective>Understand the importance of, and how to provide, confidentiality, authenticity,
integrity, and availability of data.
      <covers standard="acm-csec2017" knowledgeArea="5" id="2"/>
    </objective>
    <objective>Develop IT security policies and analyze their adherence to legal, ethical, and other
constraints.
      <covers standard="acm-csec2017" knowledgeArea="5" id="3"/>
      <covers standard="acm-csec2017" knowledgeArea="5" id="4"/>
      <covers standard="acm-csec2017" knowledgeArea="5" id="5"/>
    </objective>
    <objective>Gain skill in researching best practices and efficacy of security controls.
      <covers standard="acm-csec2017" knowledgeArea="5" id="11"/>
    </objective>
    <objective>Apply risk management concepts in a security and information assurance context.
      <covers standard="acm-csec2017" knowledgeArea="7/1" id="3"/>
    </objective>
    <objective>Conduct and support investigations in to security breaches and assess their
consequences.
      <covers standard="acm-csec2017" knowledgeArea="1/2" id="1"/>
    </objective>
    <objective>Develop strategies to plan for and recover from security related catastrophic events.
      <covers standard="acm-csec2017" knowledgeArea="5" id="17"/>
    </objective>
    <objective>Gain skill in educating a non-technical audience over IT policy.
      <covers standard="acm-csec2017" knowledgeArea="6/4" id="2"/>
    </objective>
    <objective>Prepare for advanced and expert-level professional IT certification</objective>
  </objectives>
  <outline>
    <topic>CASP / CISSP topic review</topic>
    <topic>Classifying and Documenting Data and Assets</topic>
    <topic>Determining Security Requirements and Controls</topic>
    <topic>IT Audits</topic>
    <topic>Data Protection and Access Controls</topic>
    <topic>Aligning Information Assurance Goals with Organizational Goals</topic>
    <topic>Developing Policies</topic>
    <topic>Implementing and Documenting Policies</topic>
    <topic>Communicating and Enforcing Policies</topic>
    <topic>Regulatory Constraints on Policies</topic>
    <topic>Professional Ethics</topic>
    <topic>Risk Analysis</topic>
    <topic>Contingency Planning</topic>
    <topic>Investigations and Forensics</topic>
    <topic>Incident Reporting</topic>
    <topic>Disaster Recovery</topic>
    <topic>Professional Communication</topic>
    <topic>Technical Training</topic>
  </outline>
</course>

=== mwsu-csmp/curriculum/mwsu_curriculum/syllabi/2017-2018/CSC305.xml
<?xml version="1.0" encoding="UTF-8"?>
<course
  xmlns="https://csmp.missouriwestern.edu"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://csmp.missouriwestern.edu/xml/curriculum/course.xsd">
  <college>LA</college>
  <subject>CSC</subject>
  <number>305</number>
  <title>Database Architecture and Concepts</title>
  <offered>spring</offered>
  <scheduleType>lecture</scheduleType>
  <catalogDescription>
This course will introduce students to database design, data modeling and database implementation.  This will include fundamentals, developmental processes, data structures, and logical design, with an emphasis on the relational database model. They will also learn fundamental Structured Query Language (SQL).  Students will then apply these concepts using various modeling techniques and tools.  The course will cumulate with the student applying the skills they have learned to design, build and use a database within a professional Database Management System environment.  </catalogDescription>
  <prerequisites>
    <prerequisiteCourse minimumGrade="C"><subject>ACT</subject><number>301</number></prerequisiteCourse>
  </prerequisites>
  <objectives>
    <objective>Demonstrate knowledge of database system concepts and terminology.</objective>
    <objective>Have an appreciation of the role of data, files, and databases in information systems.</objective>
    <objective>Understand the overall process of designing a relational database at various degrees of abstraction.</objective>
    <objective>Have a working knowledge of the relational data model, data integrity, constraints and relational algebra.</objective>
    <objective>Demonstrate data modeling using several types of models, including various types of Entity-Relationship Diagrams, Dependency Diagrams, the extended ERD and relational schemas.</objective>
    <objective>Understand the process of Normalization.</objective>
    <objective>Research and utilize various CASE tools to create diagrams.</objective>
    <objective>Demonstrate an ability to read a data model of any size and complexity with confidence.</objective>
    <objective>Exhibit knowledge of Structured Query Language (SQL).</objective>
    <objective>Demonstrate a working knowledge of the entire process of analysis and design of a relational database system, then physical implementation and data extraction in a professional DBMS environment.</objective>
  </objectives>
  <outline>
    <topic>stub</topic>
  </outline>
</course>
