=== mwsu-csmp/curriculum/mwsu_curriculum/schema/course.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="https://csmp.missouriwestern.edu"
  xmlns="https://csmp.missouriwestern.edu"
  elementFormDefault="qualified">

  <xs:simpleType name="courseSubject">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z][A-Z][A-Z]"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="courseNumber">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9][0-9][0-9]E?"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="prerequisiteCourse">
    <xs:sequence>
      <xs:element name="subject" type="courseSubject"/>
      <xs:element name="number" type="courseNumber"/>
    </xs:sequence>
    <xs:attribute name="corequisite" type="xs:boolean" default="false"/>
    <xs:attribute name="minimumGrade" default="pass">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="A"/>
          <xs:enumeration value="B"/>
          <xs:enumeration value="C"/>
          <xs:enumeration value="pass"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>

  <xs:simpleType name="prerequisiteGeneral">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>

  <xs:complexType name="prerequisiteConjunction">
      <xs:sequence>
        <xs:element name="prerequisiteCourse" type="prerequisiteCourse" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="prerequisiteGeneral" type="prerequisiteGeneral" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="prerequisiteConjunction" type="prerequisiteConjunction" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="prerequisiteDisjunction" type="prerequisiteDisjunction" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
  </xs:complexType>

  <xs:complexType name="prerequisiteDisjunction">
      <xs:sequence>
        <xs:element name="prerequisiteCourse" type="prerequisiteCourse" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="prerequisiteGeneral" type="prerequisiteGeneral" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="prerequisiteConjunction" type="prerequisiteConjunction" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="prerequisiteDisjunction" type="prerequisiteDisjunction" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
  </xs:complexType>

  <xs:complexType name="topic" mixed="true">
    <xs:sequence>
      <xs:element name="topic" type="topic" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="covers" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:attribute name="standard" type="xs:string"/>
          <xs:attribute name="knowledgeArea" type="xs:string"/>
          <xs:attribute name="id" type="xs:string"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="course">
    <xs:complexType>
      <xs:sequence>

      <xs:element name="college">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="CSB"/>
            <xs:enumeration value="FA"/>
            <xs:enumeration value="LA"/>
            <xs:enumeration value="PS"/>
            <xs:enumeration value="WI"/>
            <xs:enumeration value="GR"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <xs:element name="subject" type="courseSubject"/>

      <xs:element name="number" type="courseNumber"/>

      <xs:element name="title" type="xs:string"/>

      <xs:element name="offered" maxOccurs="5">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="fall"/>
            <xs:enumeration value="fall-even"/>
            <xs:enumeration value="fall-odd"/>
            <xs:enumeration value="spring"/>
            <xs:enumeration value="spring-even"/>
            <xs:enumeration value="spring-odd"/>
            <xs:enumeration value="summer"/>
            <xs:enumeration value="discretion"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <xs:element name="scheduleType">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="lecture"/>
            <xs:enumeration value="lab"/>
            <xs:enumeration value="independent study"/>
            <xs:enumeration value="online"/>
            <xs:enumeration value="seminar"/>
            <xs:enumeration value="research"/>
	    <xs:enumeration value="internship"/>
            <xs:enumeration value="practicum"/>
            <xs:enumeration value="field experience"/>
            <xs:enumeration value="discussion"/>
            <xs:enumeration value="other"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <xs:element name="catalogDescription" type="xs:string"/>

      <xs:element name="prerequisites">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="prerequisiteCourse" type="prerequisiteCourse" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="prerequisiteGeneral" type="prerequisiteGeneral" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="prerequisiteConjunction" type="prerequisiteConjunction" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="prerequisiteDisjunction" type="prerequisiteDisjunction" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>


      <xs:element name="textbook" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="author" type="xs:string" maxOccurs="unbounded"/>
          </xs:sequence>
          <xs:attribute name="title" type="xs:string"/>
          <xs:attribute name="year" type="xs:string"/>
          <xs:attribute name="publisher" type="xs:string"/>
          <xs:attribute name="edition" type="xs:string" default="1"/>
          <xs:attribute name="ISBN" type="xs:string"/>
	</xs:complexType>
      </xs:element>


      <xs:element name="objectives">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="objective" maxOccurs="unbounded">
              <xs:complexType mixed="true">
                <xs:sequence>
                <xs:element name="covers" minOccurs="0" maxOccurs="unbounded">
                  <xs:complexType>
                    <xs:attribute name="standard" type="xs:string"/>
                    <xs:attribute name="knowledgeArea" type="xs:string"/>
                    <xs:attribute name="id" type="xs:string"/>
    	            </xs:complexType>
                </xs:element>
              </xs:sequence>
            </xs:complexType>
            </xs:element>
          </xs:sequence>
	      </xs:complexType>
      </xs:element>

      <xs:element name="outline">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="topic" type="topic" maxOccurs="unbounded"/>
          </xs:sequence>
	</xs:complexType>
      </xs:element>

    </xs:sequence>

    <xs:attribute name="gradingType" default="A-Z">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="A-Z"/>
	  <xs:enumeration value="CR/F"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>

    <xs:attribute name="repeatable" type="xs:boolean" default="false"/>
    <xs:attribute name="equivalentCourse" type="xs:string" default=""/>
    <xs:attribute name="creditHoursLecture" type="xs:decimal" default="3"/>
    <xs:attribute name="creditHoursLab" type="xs:decimal" default="0"/>
    <xs:attribute name="creditHoursOther" type="xs:decimal" default="0"/>
    <xs:attribute name="contactHoursLecture" type="xs:decimal" default="3"/>
    <xs:attribute name="contactHoursLab" type="xs:decimal" default="0"/>
    <xs:attribute name="contactHoursOther" type="xs:decimal" default="0"/>
    <xs:attribute name="workloadHoursLecture" type="xs:decimal" default="3"/>
    <xs:attribute name="workloadHoursLab" type="xs:decimal" default="0"/>
    <xs:attribute name="workloadHoursOther" type="xs:decimal" default="0"/>
    <xs:attribute name="workloadHoursExpected" type="xs:decimal"/>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== mwsu-csmp/curriculum/syllabi/CSC484.xml
<?xml version="1.0" encoding="UTF-8"?>
<course
  xmlns="https://csmp.missouriwestern.edu"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://csmp.missouriwestern.edu/xml/curriculum/course.xsd">
  <college>LA</college>
  <subject>CSC</subject>
  <number>487</number>
  <title>Digital Animation and Production</title>
  <offered>discretion</offered>
  <scheduleType>lecture</scheduleType>
  <catalogDescription>
This class will concentrate on the methods used to build digital animated characters. Subjects will include character design and development, animation of characters, lighting, camera shots, sound and production editing.
  </catalogDescription>
  <prerequisites>
  </prerequisites>
  <objectives>
    <objective>stub</objective>
  </objectives>
  <outline>
    <topic>stub</topic>
  </outline>
</course>

=== mwsu-csmp/curriculum/mwsu_curriculum/syllabi/2021-2022/CSC490.xml
<?xml version="1.0" encoding="UTF-8"?>
<course
  xmlns="https://csmp.missouriwestern.edu"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://csmp.missouriwestern.edu/xml/curriculum/course.xsd"
  creditHoursLecture="1"
  workloadHoursLecture="1">
  <college>LA</college>
  <subject>ACT</subject>
  <number>490</number>
  <title>Computer Science Career Preparation</title>
  <offered>fall</offered>
  <scheduleType>lecture</scheduleType>
  <catalogDescription>In this course students will begin applying their MWSU education towards building a career in CS. Students will learn how to navigate a career path in CS, explore alternative career paths, and explore opportunities for continuing education and professional development. Students will develop application materials and attempt entrance, exit, and / or certification exams in preparation for graduation, applying to jobs, and applying to graduate schools. 
  </catalogDescription>
  <prerequisites>
  </prerequisites>
  <objectives>
    <objective>Determine what types of jobs in CS best match their short and long term career and professional development goals</objective>
    <objective>Locate and navigate resources for finding CS jobs in their desired location</objective>
    <objective>Effectively communicate their skill set and value as an employee to potential employers through letters, resumes, networking, interviews, and other means</objective>
    <objective>Explain the concept that because you can do it, it doesnâ€™t mean you should do it.
      <covers standard="acm-csec2017" knowledgeArea="2/7" id="1"/>
    </objective>
    <objective>Paraphrase professional ethics and codes of conduct from prominent professional societies, such as ACM, IEEE-CS, AIS and (ISC)
      <covers standard="acm-csec2017" knowledgeArea="8/3" id="2"/>
    </objective>
    <objective>Describe ways in which decision-making algorithms could over-represent or under-represent majority and minority groups in society.
      <covers standard="acm-csec2017" knowledgeArea="8/3" id="3"/>
    </objective>
    <objective>Locate and utilize resources for continuing education and professional development to gain or improve specific skillsets in CS or transition in to other career fields (ex. Law)</objective>
    <objective>Prepare effectively for certification exams, assessments, and technical interviews</objective>
  </objectives>
  <outline>
    <topic>Searching for CS employment opportunities</topic>
    <topic>Emerging and popular CS skillsets and technologies</topic>
    <topic>Communication
        <topic>Developing CS resumes</topic>
        <topic>Developing CS cover letters</topic>
        <topic>Developing a project portfolio</topic>
        <topic>Applying to graduate schools</topic>
        <topic>Developing a web and social media presence</topic>
    </topic>
    <topic>Networking
        <topic>Professional organizations</topic>
        <topic>Conferences, job fairs, and other professional gatherings</topic>
    </topic>
    <topic>Professional ethics and employment regulations</topic>
    <topic>Preparing for entrance, exit, and certification exams</topic>
  </outline>
</course>

=== mwsu-csmp/curriculum/mwsu_curriculum/syllabi/2018-2019/CSC487.xml
<?xml version="1.0" encoding="UTF-8"?>
<course
  xmlns="https://csmp.missouriwestern.edu"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://csmp.missouriwestern.edu/xml/curriculum/course.xsd">
  <college>LA</college>
  <subject>CSC</subject>
  <number>487</number>
  <title>Digital Animation and Production</title>
  <offered>fall-even</offered>
  <scheduleType>lecture</scheduleType>
  <catalogDescription>
This class will concentrate on the methods used to build digital animated characters. Subjects will include character design and development, animation of characters, lighting, camera shots, sound and production editing.
  </catalogDescription>
  <prerequisites>
    <prerequisiteCourse minimumGrade="C"><subject>CSC</subject><number>254</number></prerequisiteCourse>
  </prerequisites>
  <objectives>
    <objective>Students will demonstrate understanding of the following principles and techniques:</objective>
    <objective>Imaging Concepts and Terminology</objective>
    <objective>Motion aesthetics, Duration,Pacing/Tempo, Sequence, The Narrative/Storyline, Temporal Relationship</objective>
    <objective>Application of software for still image/time based media and animation</objective>
    <objective>Project Development</objective>
  </objectives>
  <outline>
    <topic>An introduction to historical references, background, and contemporary concepts of animation</topic>
    <topic>Storyboarding</topic>
    <topic>Stop motion animation</topic>
    <topic>Digital animation methods</topic>
    <topic>Framing and Composition</topic>
    <topic>Basic Lighting</topic>
    <topic>Professional Production Techniques (sizing for output, video and audio capture, photo import and animation of still images)</topic>
    <topic>Rendering</topic>
  </outline>
</course>

=== mwsu-csmp/curriculum/mwsu_curriculum/syllabi/2020-2021/CSC346.xml
<?xml version="1.0" encoding="UTF-8"?>
<course
  xmlns="https://csmp.missouriwestern.edu"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://csmp.missouriwestern.edu/xml/curriculum/course.xsd">
  <college>LA</college>
  <subject>CSC</subject>
  <number>254</number>
  <title>Enterprise System Computing with Java</title>
  <offered>spring-even</offered>
  <scheduleType>lecture</scheduleType>
  <catalogDescription>This course covers the front and back end development of large software systems. The course includes data exchange and the use of APIs. Use of frameworks and professional development tools is emphasized.
  </catalogDescription>
  <prerequisites>
    <prerequisiteCourse minimumGrade="C"><subject>CSC</subject><number>254</number></prerequisiteCourse>
    <prerequisiteCourse minimumGrade="C"><subject>CSC</subject><number>305</number></prerequisiteCourse>
  </prerequisites>

  <objectives>
    <objective>Describe the differences between relational and semi-structured data models.
      <covers standard="acm-cs2013" knowledgeArea="IM/DM" id="7"/>
    </objective>
    <objective>Give a semi-structured equivalent (eg, in DTD or XML Schema) for a given relational schema.
      <covers standard="acm-cs2013" knowledgeArea="IM/DM" id="8"/>
    </objective>
    <objective>Describe how platform-based development differs from general purpose programming.
      <covers standard="acm-cs2013" knowledgeArea="PBD/I" id="1"/>
    </objective>
    <objective>List characteristics of platform languages.
      <covers standard="acm-cs2013" knowledgeArea="PBD/I" id="2"/>
    </objective>
    <objective>Write and execute a simple platform-based program.
      <covers standard="acm-cs2013" knowledgeArea="PBD/I" id="3"/>
    </objective>
    <objective>List the advantages and disadvantages of programming with platform constraints.
      <covers standard="acm-cs2013" knowledgeArea="PBD/I" id="4"/>
    </objective>
    <objective>Describe an interactive system in terms of a model, a view, and a controller.
      <covers standard="acm-cs2013" knowledgeArea="PL/EDRP" id="3"/>
    </objective>
    <objective>Design and Implement a simple web application.
      <covers standard="acm-cs2013" knowledgeArea="PBD/WP" id="1"/>
    </objective>
    <objective>Describe the constraints that the web puts on developers.
      <covers standard="acm-cs2013" knowledgeArea="PBD/WP" id="2"/>
    </objective>
    <objective>Compare and contrast web programming with general purpose programming.
      <covers standard="acm-cs2013" knowledgeArea="PBD/WP" id="3"/>
    </objective>
    <objective>Describe the differences between Software-as-a-Service and traditional software products.
      <covers standard="acm-cs2013" knowledgeArea="PBD/WP" id="4"/>
    </objective>
    <objective>Discuss how web standards impact software development.
      <covers standard="acm-cs2013" knowledgeArea="PBD/WP" id="5"/>
    </objective>
    <objective>Review an existing web application against a current web standard.
      <covers standard="acm-cs2013" knowledgeArea="PBD/WP" id="6"/>
    </objective>
  </objectives>
  <outline>
    <topic>stub</topic>
  </outline>
</course>

=== mwsu-csmp/curriculum/mwsu_curriculum/syllabi/2021-2022/ACT405.xml
<?xml version="1.0" encoding="UTF-8"?>
<course
  xmlns="https://csmp.missouriwestern.edu"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://csmp.missouriwestern.edu/xml/curriculum/course.xsd">
  <college>LA</college>
  <subject>ACT</subject>
  <number>405</number>
  <title>Business Intelligence</title>
  <offered>discretion</offered>
  <scheduleType>lecture</scheduleType>
  <catalogDescription>
Students learn how to make better business decisions, use fewer resources, and improve the company's bottom line by developing and using a data warehouse. This course provides an overview of business intelligence and data warehousing and gives students a look at all the major facets of developing and using a data warehouse to make effective business decisions.
  </catalogDescription>
  <prerequisites>
    <prerequisiteCourse minimumGrade="C"><subject>CSC</subject><number>305</number></prerequisiteCourse>
  </prerequisites>
  <objectives>
    <objective>Use application development tools and techniques in a hands-on learning environment to develop webâ€”based database Bl applications.</objective>
    <objective>Utilized spreadsheet and database skills learned in previous coursework to create internet based portal for use by business decision makers</objective>
    <objective>Develop an understanding of the importance of security measures that must be taken toensure information integrity and privacy in applications.</objective>
    <objective>Develop an awareness of the importance of quality in application development.</objective>
    <objective>Become an informed developer of information portals.</objective>
    <objective>Usage of the technology current in the industry.</objective>
    <objective>Become familiar with the concepts and techniques used to implement BusinessIntelligence.</objective>
    <objective>Understand the importance of skill requirements and team dynamics.</objective>
    <objective>Understand the critical success factors and goals for a Business Intelligence system</objective>
  </objectives>
  <outline>
    <topic></topic>
  </outline>
</course>

=== mwsu-csmp/curriculum/mwsu_curriculum/syllabi/2019-2020/MAT165.xml
<?xml version="1.0" encoding="UTF-8"?>
<course
  xmlns="https://csmp.missouriwestern.edu"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://csmp.missouriwestern.edu/xml/curriculum/course.xsd">
  <college>LA</college>
  <subject>MAT</subject>
  <number>165</number>
  <title>Calculus with Analytic Geometry I: Differentiation</title>
  <offered>fall</offered>
  <scheduleType>lecture</scheduleType>
  <catalogDescription>Includes the study of limits and continuity of real functions, the derivative of algebraic and trigonometric functions, and applications of the derivative. Not open to the student with credit in MAT 167.</catalogDescription>
  <prerequisites>
    <prerequisiteDisjunction>
      <prerequisiteGeneral>an ACT math subscore of at least 25</prerequisiteGeneral>
      <prerequisiteConjunction>
        <prerequisiteCourse minimumGrade="C">
          <subject>MAT</subject>
          <number>116</number>
        </prerequisiteCourse>
        <prerequisiteCourse corequisite="true" minimumGrade="C">
          <subject>MAT</subject>
          <number>119</number>
        </prerequisiteCourse>
      </prerequisiteConjunction>
    </prerequisiteDisjunction>
  </prerequisites>
  <objectives>
    <objective>Compute limits of algebraic and trigonometric functions.</objective>
    <objective>Utilize the definition of derivative to derive or prove mathematical statements.</objective>
    <objective>Find derivatives of algebraic and trigonometric functions.</objective>
    <objective>Identify and use interpretations of the derivative to solve problems related to curve sketching, related rates, and optimization.</objective>
    <objective>Utilize mathematical language and symbolism to communicate ideas and represent relationships.</objective>
    <objective>Interact verbally with others to clarify and extend understanding of mathematical situations.</objective>
  </objectives>
  <outline>
    <topic>stub
      <topic>stub</topic>
    </topic>
  </outline>
</course>

=== mwsu-csmp/curriculum/mwsu_curriculum/syllabi/2019-2020/ACT302.xml
<?xml version="1.0" encoding="UTF-8"?>
<course
  xmlns="https://csmp.missouriwestern.edu"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://csmp.missouriwestern.edu/xml/curriculum/course.xsd">
  <college>LA</college>
  <subject>ACT</subject>
  <number>302</number>
  <title>Decision Support Systems</title>
  <offered>spring</offered>
  <scheduleType>lecture</scheduleType>
  <catalogDescription>
This course uses statistics to help solve business problems, examines case examples of statistical analysis in areas such as marketing, finance and management, and teaches descriptive and inferential techniques using a statistical computer software application - Excel. Topics to be covered include Creating Charts, Working with Charts, Using List Features and Templates, Working with Advanced Functions, Analyzing Data, Using PivotTables, and Working with Data Analysis Tools.
  </catalogDescription>
  <prerequisites>
    <prerequisiteCourse minimumGrade="C"><subject>CSC</subject><number>201</number></prerequisiteCourse>
  </prerequisites>
  <objectives>
    <objective>stub</objective>
  </objectives>
  <outline>
    <topic>stub</topic>
  </outline>
</course>

=== mwsu-csmp/curriculum/syllabi/CSC346.xml
<?xml version="1.0" encoding="UTF-8"?>
<course
  xmlns="https://csmp.missouriwestern.edu"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://csmp.missouriwestern.edu/xml/curriculum/course.xsd">
  <college>LA</college>
  <subject>CSC</subject>
  <number>254</number>
  <title>Enterprise System Computing with Java</title>
  <offered>spring-even</offered>
  <scheduleType>lecture</scheduleType>
  <catalogDescription>This course covers the front and back end development of large software systems. The course includes data exchange and the use of APIs. Use of frameworks and professional development tools is emphasized.
  </catalogDescription>
  <prerequisites>
    <prerequisiteCourse minimumGrade="C"><subject>CSC</subject><number>254</number></prerequisiteCourse>
      <prerequisiteCourse minimumGrade="C"><subject>CSC</subject><number>305</number></prerequisiteCourse>
  </prerequisites>

  <objectives>
    <objective mastery="">Describe the differences between relational and semi-structured data models.
      <covers standard="acm:2013" knowledgeArea="IM/DM" id="7"/>
    </objective>
    <objective mastery="">Give a semi-structured equivalent (eg, in DTD or XML Schema) for a given relational schema.
      <covers standard="acm:2013" knowledgeArea="IM/DM" id="8"/>
    </objective>
    <objective mastery="">Describe how platform-based development differs from general purpose programming.
      <covers standard="acm:2013" knowledgeArea="PBD/I" id="1"/>
    </objective>
    <objective mastery="">List characteristics of platform languages.
      <covers standard="acm:2013" knowledgeArea="PBD/I" id="2"/>
    </objective>
    <objective mastery="">Write and execute a simple platform-based program.
      <covers standard="acm:2013" knowledgeArea="PBD/I" id="3"/>
    </objective>
    <objective mastery="">List the advantages and disadvantages of programming with platform constraints.
      <covers standard="acm:2013" knowledgeArea="PBD/I" id="4"/>
    </objective>
    <objective mastery="">Describe an interactive system in terms of a model, a view, and a controller.
      <covers standard="acm:2013" knowledgeArea="PL/EDRP" id="3"/>
    </objective>
    <objective mastery="">Design and Implement a simple web application.
      <covers standard="acm:2013" knowledgeArea="PBD/WP" id="1"/>
    </objective>
    <objective mastery="">Describe the constraints that the web puts on developers.
      <covers standard="acm:2013" knowledgeArea="PBD/WP" id="2"/>
    </objective>
    <objective mastery="">Compare and contrast web programming with general purpose programming.
      <covers standard="acm:2013" knowledgeArea="PBD/WP" id="3"/>
    </objective>
    <objective mastery="">Describe the differences between Software-as-a-Service and traditional software products.
      <covers standard="acm:2013" knowledgeArea="PBD/WP" id="4"/>
    </objective>
    <objective mastery="">Discuss how web standards impact software development.
      <covers standard="acm:2013" knowledgeArea="PBD/WP" id="5"/>
    </objective>
    <objective mastery="">Review an existing web application against a current web standard.
      <covers standard="acm:2013" knowledgeArea="PBD/WP" id="6"/>
    </objective>
  </objectives>
  <outline>
    <topic>stub</topic>
  </outline>
</course>
