=== mwsu-csmp/curriculum/mwsu_curriculum/schema/program.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="https://csmp.missouriwestern.edu"
  xmlns="https://csmp.missouriwestern.edu"
  elementFormDefault="qualified">

  <xs:simpleType name="courseSubject">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z][A-Z][A-Z]"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="courseNumber">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{3}E?"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="courseName">
    <xs:sequence>
      <xs:element name="subject" type="courseSubject"/>
      <xs:element name="number" type="courseNumber"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="conjunction">
    <xs:sequence>
      <xs:element name="course" type="courseName" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="disjunction">
    <xs:sequence>
      <xs:choice maxOccurs="unbounded">
        <xs:element name="conjunction" type="conjunction"/>
        <xs:element name="course" type="courseName"/>
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="requirement">
    <xs:sequence>
      <xs:choice maxOccurs="unbounded">
        <xs:element name="disjunction" type="disjunction"/>
        <xs:element name="course" type="courseName"/>
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="section">
    <xs:sequence>
      <xs:element name="requirement" type="requirement" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="blank" type="xs:integer" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="header" type="xs:string"/>
  </xs:complexType>

  <xs:element name="program">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="section" type="section" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="parent" type="xs:string" default=""/>
      <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== mwsu-csmp/curriculum/mwsu_curriculum/programs/2017-2018/cs.xml
<?xml version="1.0" encoding="UTF-8"?>
<program
  name="cs"
  parent="cs-core"
  xmlns="https://csmp.missouriwestern.edu"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://csmp.missouriwestern.edu/xml/curriculum/mwsu_curriculum/transformations/program.xsd">
  <section header="Computer Information Systems Concentration">
    <requirement>
      <disjunction>
        <course><subject>MAT</subject><number>167</number></course>
        <conjunction>
          <course><subject>MAT</subject><number>165</number></course>
          <course><subject>MAT</subject><number>166</number></course>
        </conjunction>
      </disjunction>
    </requirement>
    <requirement><course><subject>CSC</subject><number>208</number></course></requirement>
    <requirement><course><subject>CSC</subject><number>384</number></course></requirement>
    <requirement><course><subject>CSC</subject><number>318</number></course></requirement>
    <requirement><course><subject>CSC</subject><number>386</number></course></requirement>
  </section>
  <section header="PLUS--9 credits of ACT, CSC, or MAT courses numbered 300 - 599">
    <blank>3</blank>
    <blank>3</blank>
    <blank>3</blank>
  </section>
</program>
