=== mwsu-csmp/curriculum/mwsu_curriculum/schema/standard.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="https://csmp.missouriwestern.edu"
  xmlns="https://csmp.missouriwestern.edu"
  elementFormDefault="qualified">

  <xs:simpleType name="id">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z]{0,6}(\d?)"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="courseName">
    <xs:restriction base="xs:string">
      <xs:whiteSpace value="replace"/>
    </xs:restriction>
  </xs:simpleType>

   <xs:simpleType name="importance">
        <xs:restriction base="xs:string">
          <xs:enumeration value='tier1'/>
          <xs:enumeration value='tier2'/>
          <xs:enumeration value='elective'/>
        </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="mastery_level">
        <xs:restriction base="xs:string">
          <xs:enumeration value='familiarity'/>
          <xs:enumeration value='assessment'/>
          <xs:enumeration value='usage'/>
        </xs:restriction>
  </xs:simpleType>


<xs:complexType name="reference">
  <xs:attribute name="standard" type="xs:string"/>
  <xs:attribute name="knowledgeArea" type="xs:string"/>
  <xs:attribute name="id" type="xs:string"/>
</xs:complexType>

  <xs:complexType name="topic" mixed="true">
    <xs:sequence>
      <xs:element name="subsumes" type="reference" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="topic" type="topic" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="importance" type="importance"/>
  </xs:complexType>

  <xs:complexType name="outcome" mixed="true">
    <xs:sequence>
      <xs:element name="subsumes" type="reference" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="importance" type="importance"/>
    <xs:attribute name="mastery_level" type="mastery_level"/>
  </xs:complexType>

  <xs:complexType name="knowledgeArea">
   <xs:sequence>
    <xs:element name="knowledgeArea" type="knowledgeArea" minOccurs="0" maxOccurs="unbounded"/>
    <xs:element name="topic" type="topic" minOccurs="0" maxOccurs="unbounded"/>
    <xs:element name="outcome" type="outcome" minOccurs="0" maxOccurs="unbounded"/>
   </xs:sequence>
   <xs:attribute name="id" type="xs:string" use="required"/>
   <xs:attribute name="name" type="xs:string"/>
  </xs:complexType>

    <xs:element name="curriculumStandard">
     <xs:complexType>
      <xs:sequence>
        <xs:element name="name" type="xs:string" />
        <xs:element name="body" type="xs:string" />
        <xs:element name="version" type="xs:string" />
        <xs:element name="documentUrl" type="xs:string" />
        <xs:element name="knowledgeArea" type="knowledgeArea" maxOccurs="unbounded">
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== mwsu-csmp/curriculum/mwsu_curriculum/standards/ceh2.0.xml
<curriculumStandard
        xmlns="https://csmp.missouriwestern.edu"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://csmp.missouriwestern.edu/xml/curriculum/standard.xsd">
  <name>Certified Ethical Hacker Exam Blueprint 2.0</name>
  <body>eccouncil</body>
  <version>2.0</version>
  <documentUrl>https://cert.eccouncil.org/images/doc/CEH-Exam-Blueprint-v2.0.pdf</documentUrl>
  <knowledgeArea name="Background"  id="1">
      <topic>Networking technologies (e.g., hardware, infrastructure)</topic>
      <topic>Web technologies (e.g., web 2.0, skype)</topic>
      <topic>Systems technologies</topic>
      <topic>Communication on protocols</topic>
      <topic>Malware operations</topic>
      <topic>Mobile technologies (e.g., smartphones )</topic>
      <topic>Telecommunication on technologies</topic>
      <topic>Backups and archiving (e.g., local, network)</topic>
  </knowledgeArea>
  <knowledgeArea name="Analysis / Assessment"  id="2">
      <topic>Data analysis</topic>
      <topic>Systems analysis</topic>
      <topic>Risk assessments</topic>
      <topic>Technical assessment methods</topic>
  </knowledgeArea>
  <knowledgeArea name="Security"  id="3">
      <topic>Systems security controls</topic>
      <topic>Application/file server</topic>
      <topic>Firewalls</topic>
      <topic>Cryptography</topic>
      <topic>Network security</topic>
      <topic>Physical security</topic>
      <topic>Threat modeling</topic>
      <topic>Verification procedures (e.g., false positive/negative validation)</topic>
      <topic>Social engineering (human factors manipulation)</topic>
      <topic>Vulnerability scanners</topic>
      <topic>Security policy implications</topic>
      <topic>Privacy/confidentiality (with regard to engagement)</topic>
      <topic>Biometrics</topic>
      <topic>Wireless access technology (e.g., networking, RFID, Bluetooth)</topic>
      <topic>Trusted networks</topic>
      <topic>Vulnerabilities</topic>
  </knowledgeArea>
  <knowledgeArea name="Tools / Systems /Programs"  id="4">
      <topic>Network/host based intrusion</topic>
      <topic>Network/wireless sniffers (e.g., WireShark, Airsnort)</topic>
      <topic>Access control mechanisims (e.g., smart cards )</topic>
      <topic>Cryptography techniques (e.g., IPsec, SSL, PGP)</topic>
      <topic>Programming languages (e.g. C++, Java, C#, C)</topic>
      <topic>Scripting languages (e.g., PHP, Java script)</topic>
      <topic>Boundary protection appliances</topic>
      <topic>Network topologies</topic>
      <topic>Subnetting</topic>
      <topic>Port scanning (e.g., NMAP)</topic>
      <topic>Domain name system (DNS)</topic>
      <topic>Routers /modems /switches</topic>
      <topic>Vulnerability scanner (e.g., Nessus, Rena)</topic>
      <topic>Vulnerability management and protection systems (e.g.,Founds tone, Ecora)</topic>
      <topic>Operating environments (e.g., Linux, Windows, Mac)</topic>
      <topic>Antivirus systems and programs</topic>
      <topic>Log analysis tools</topic>
      <topic>Security models</topic>
      <topic>Exploitation tools</topic>
      <topic>Database structures</topic>
  </knowledgeArea>
  <knowledgeArea name="Procedures /Methodology"  id="5">
      <topic>Cryptography</topic>
      <topic>Public key infrastructure (PKI)</topic>
      <topic>Security Architecture (SA)</topic>
      <topic>Service Oriented Architecture</topic>
      <topic>Information security incident</topic>
      <topic>N-tier application design</topic>
      <topic>TCP/IP networking (e.g., network routing)</topic>
      <topic>Security testing methodology</topic>
  </knowledgeArea>
  <knowledgeArea name="Regulation / Policy"  id="6">
      <topic>Security policies</topic>
      <topic>Compliance regulations (e.g., PCI)</topic>
  </knowledgeArea>
  <knowledgeArea name="Ethics"  id="7">
      <topic>Professional code of conduct</topic>
      <topic>Appropriateness of hacking</topic>
  </knowledgeArea>
</curriculumStandard>

=== mwsu-csmp/curriculum/mwsu_curriculum/standards/security+601.xml
<curriculumStandard
        xmlns="https://csmp.missouriwestern.edu"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://csmp.missouriwestern.edu/xml/curriculum/standard.xsd">
  <name>CompTIA Security + 601 Exam Objectives</name>
  <body>CompTIA</body>
  <version>601</version>
  <documentUrl>https://drive.google.com/file/d/1EOMj_ur0ep3pV9WpxD7jqfCJ9NXgzBm7/view?usp=sharing</documentUrl>
  <knowledgeArea name="Attacks, Threats, and Vulnerabilities"  id="1">
      <topic>Compare and contrast different types of social engineering techniques</topic>
      <topic>Given a scenario, analyze potential indicators to determine the type of attack.</topic>
      <topic>Given a scenario, analyze potential indicators associated with application attacks.</topic>
      <topic>Given a scenario, analyze potential indicators associated with network attacks.</topic>
      <topic>Explain different threat actors, vectors, and intelligence sources.</topic>
      <topic>Explain the security concerns associated with various types of vulnerabilities.</topic>
      <topic>Summarize the techniques used in security assessments.</topic>
      <topic>Explain the techniques used in penetration testing.</topic>      
  </knowledgeArea>
  <knowledgeArea name="Architecture and Design"  id="2">
      <topic>Explain the importance of security concepts in an enterprise environment.</topic>
      <topic>Summarize virtualization and cloud computing concepts.</topic>
      <topic>ESummarize secure application development, deployment, and automation concepts.</topic>
      <topic>Summarize authentication and authorization design concepts.</topic>
      <topic>Given a scenario, implement cybersecurity resilience.</topic>
      <topic>Explain the security implications of embedded and specialized systems.</topic>
      <topic>Explain the importance of physical security controls.</topic>
      <topic>Summarize the basics of cryptographic concepts.</topic>
  </knowledgeArea>
  <knowledgeArea name="Implementation"  id="3">
      <topic>Given a scenario, implement secure protocols.</topic>
      <topic>Given a scenario, implement host or application security solutions.</topic>
      <topic>Given a scenario, implement secure network designs.</topic>
      <topic>Given a scenario, install and configure wireless security settings.</topic>
      <topic>Given a scenario, implement secure mobile solutions.</topic>
      <topic>Given a scenario, apply cybersecurity solutions to the cloud.</topic>
      <topic>Given a scenario, implement identity and account management controls.</topic>
      <topic>Given a scenario, implement authentication and authorization solutions.</topic>
      <topic>Given a scenario, implement public key infrastructure.</topic>
  </knowledgeArea>
  <knowledgeArea name="Operations and Incident Response"  id="4">
      <topic>Given a scenario, use the appropriate tool to assess organizational security.</topic>
      <topic>Summarize the importance of policies, processes, and procedures for incident response.</topic>
      <topic>Given an incident, utilize appropriate data sources to support an investigation.</topic>
      <topic>Given an incident, apply mitigation techniques or controls to secure an environment.</topic>
      <topic>Explain the key aspects of digital forensics.</topic>
  </knowledgeArea>
  <knowledgeArea name="Governance, Risk, and Compliance"  id="5">
      <topic>Compare and contrast various types of controls.</topic>
      <topic>Explain the importance of applicable regulations, standards, or frameworks that impact organizational security posture.</topic>
      <topic>Explain the importance of policies to organizational security.</topic>
      <topic>Summarize risk management processes and concepts.</topic>
      <topic>Explain privacy and sensitive data concepts in relation to security.</topic>
  </knowledgeArea>
</curriculumStandard>
